# Generated by Django 3.1.2 on 2020-10-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sunnyfive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, default='', max_digits=10, null=True)),
                ('lng', models.DecimalField(decimal_places=6, default='', max_digits=10, null=True)),
                ('url', models.CharField(default='', max_length=100, null=True)),
                ('title', models.CharField(default='', max_length=30, null=True)),
                ('nation', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
    ]
