# Generated by Django 3.1.2 on 2020-10-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunnyfive', '0002_auto_20201008_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunnyfive',
            name='title',
            field=models.CharField(default='', max_length=70, null=True),
        ),
    ]
